export enum ETipoArma {
    dagger = 1,
    one_handed_sword = 2,
    two_handed_sword = 3,
    one_handed_spear = 4,
    two_handed_spear = 5,
    one_handed_axes = 6,
    two_handed_axes = 7,
    mace = 8,
    one_handed_staff = 9,
    two_handed_staff = 10,
    bow = 11,
    knuckle = 12,
    musical_instrument = 13,
    whip = 14,
    book = 15,
    katar = 16,
    fuuma_shuriken = 17,
    revolver = 18,
    rifle = 19,
    gatling_gun = 20,
    shotgun = 21,
    grenade_launcher = 22
}